redis:
  restart: always
  tty: true
  image: redis
  stdin_open: true
pyapp:
  restart: always
  tty: true
  image: 172.31.7.232:5000/python-redis-demo:b$$BUILD_NUMBER$$
  links:
  - 'redis:'
  stdin_open: true
pyapplb:
  ports:
  - $$PORT_NUMBER$$:5000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - pyapp:pyapp
  stdin_open: true
